-- 1. 商品分类表
DROP TABLE IF EXISTS "ea_mall_cate";
CREATE TABLE "ea_mall_cate"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(20) NOT NULL,
    "image" varchar(500) DEFAULT NULL,
    "sort" int DEFAULT 0,
    "status" smallint DEFAULT 1,
    "remark" varchar(255) DEFAULT NULL,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL
);
CREATE UNIQUE INDEX "ea_idx_mall_cate_title" ON "ea_mall_cate" ("title");

INSERT INTO "ea_mall_cate" ("title", "image", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES ('电器', '/static/common/images/logo-1.png', 0, 1, '', 1589440437, 1589440437, null);
INSERT INTO "ea_mall_cate" ("title", "image", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES ('3C', '/static/common/images/logo-1.png', 0, 1, '', 1589440437, 1589440437, null);

-- 2. 商品表
DROP TABLE IF EXISTS "ea_mall_goods";
CREATE TABLE "ea_mall_goods"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cate_id" int DEFAULT NULL,
    "title" varchar(20) NOT NULL,
    "logo" varchar(500) DEFAULT NULL,
    "images" text,
    "describe" text,
    "market_price" decimal(10, 2) DEFAULT '0.00',
    "discount_price" decimal(10, 2) DEFAULT '0.00',
    "sales" int DEFAULT 0,
    "virtual_sales" int DEFAULT 0,
    "stock" int DEFAULT 0,
    "total_stock" int DEFAULT 0,
    "sort" int DEFAULT 0,
    "status" smallint DEFAULT 1,
    "remark" varchar(255) DEFAULT NULL,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL
);
CREATE INDEX "ea_idx_mall_goods_cate_id" ON "ea_mall_goods" ("cate_id");

INSERT INTO "ea_mall_goods" ("cate_id", "title", "logo", "images", "describe", "market_price", "discount_price", "sales", "virtual_sales", "stock", "total_stock", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES (1, '落地-风扇', '/static/common/images/logo-1.png', '/static/common/images/logo-1.png|/static/common/images/logo-1.png|/static/common/images/logo-1.png|/static/common/images/logo-1.png',
        '<p>76654757</p>\n\n<p><img alt=\"\" src=\"/static/common/images/logo-1.png\" style=\"height:689px; width:790px\" /></p>\n\n<p><img alt=\"\" src=\"/static/common/images/logo-1.png\" style=\"height:877px; width:790px\" /></p>\n', '599.00', '368.00', 0, 594, 0, 0, 675, 1, '', 1589454309, 1589567016, null);
INSERT INTO "ea_mall_goods" ("cate_id", "title", "logo", "images", "describe", "market_price", "discount_price", "sales", "virtual_sales", "stock", "total_stock", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES (2, '电脑', '/static/common/images/logo-1.png', '/static/common/images/logo-1.png', '<p>477</p>\n', '0.00', '0.00', 0, 0, 115, 320, 0, 1, '', 1589465215, 1589476345, null);

-- 3. 管理员表
DROP TABLE IF EXISTS "ea_system_admin";
CREATE TABLE "ea_system_admin"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "auth_ids" varchar(255) DEFAULT NULL,
    "head_img" varchar(255) DEFAULT NULL,
    "username" varchar(50) NOT NULL DEFAULT '',
    "password" varchar(255) NOT NULL DEFAULT '',
    "phone" varchar(16) DEFAULT NULL,
    "remark" varchar(255) DEFAULT '',
    "login_num" bigint DEFAULT 0,
    "sort" int DEFAULT 0,
    "status" smallint NOT NULL DEFAULT 1,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL,
    "login_type" smallint NOT NULL DEFAULT 1,
    "ga_secret" varchar(32) NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX "ea_idx_system_admin_username" ON "ea_system_admin" ("username");
CREATE INDEX "ea_idx_system_admin_phone" ON "ea_system_admin" ("phone");

INSERT INTO "ea_system_admin" ("auth_ids", "head_img", "username", "password", "phone", "remark", "login_num", "sort", "status", "create_time", "update_time", "delete_time", "login_type", "ga_secret")
VALUES (null, '/static/admin/images/head.jpg', 'admin', 'a33b679d5581a8692988ec9f92ad2d6a2259eaa7', 'admin', 'admin', 0, 0, 1, 1589454169, 1589476815, null,1,'');

-- 4. 权限表
DROP TABLE IF EXISTS "ea_system_auth";
CREATE TABLE "ea_system_auth"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(20) NOT NULL,
    "sort" int DEFAULT 0,
    "status" smallint DEFAULT 1,
    "remark" varchar(255) DEFAULT NULL,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL
);
CREATE UNIQUE INDEX "ea_idx_system_auth_title" ON "ea_system_auth" ("title");

INSERT INTO "ea_system_auth" ("title", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES ('管理员', 1, 1, '测试管理员', 1588921753, 1589614331, null);
INSERT INTO "ea_system_auth" ("title", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES ('游客权限', 0, 1, '', 1588227513, 1589591751, 1589591751);

-- 5. 权限节点关联表
DROP TABLE IF EXISTS "ea_system_auth_node";
CREATE TABLE "ea_system_auth_node"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "auth_id" bigint DEFAULT NULL,
    "node_id" bigint DEFAULT NULL
);
CREATE INDEX "ea_index_system_auth_auth" ON "ea_system_auth_node" ("auth_id");
CREATE INDEX "ea_index_system_auth_node" ON "ea_system_auth_node" ("node_id");

INSERT INTO "ea_system_auth_node" ("auth_id", "node_id")
VALUES (6, 1),(6, 2),(6, 9),(6, 12),(6, 18),(6, 19),(6, 21),(6, 22),(6, 29),(6, 30),(6, 38),(6, 39),(6, 45),(6, 46),(6, 52),(6, 53);

-- 6. 系统配置表
DROP TABLE IF EXISTS "ea_system_config";
CREATE TABLE "ea_system_config"
(
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(30) NOT NULL DEFAULT '',
    "group" varchar(30) NOT NULL DEFAULT '',
    "value" text,
    "remark" varchar(100) DEFAULT '',
    "sort" int DEFAULT 0,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL
);
CREATE UNIQUE INDEX "ea_idx_system_config_name" ON "ea_system_config" ("name");
CREATE INDEX "ea_idx_system_config_group" ON "ea_system_config" ("group");

INSERT INTO "ea_system_config" ("name", "group", "value", "remark", "sort", "create_time", "update_time")
VALUES ('alisms_access_key_id', 'sms', '填你的', '阿里大于公钥', 0, null, null),
       ('alisms_access_key_secret', 'sms', '填你的', '阿里大鱼私钥', 0, null, null),
       ('upload_type', 'upload', 'local', '当前上传方式 （local,oss,cos）', 0, null, null),
       ('upload_allow_ext', 'upload', 'doc,gif,ico,icon,jpg,mp3,mp4,p12,pem,png,rar,jpeg', '允许上传的文件类型', 0, null, null),
       ('upload_allow_size', 'upload', '1024000', '允许上传的大小', 0, null, null),
       ('upload_allow_mime', 'upload', 'image/gif,image/jpeg,video/x-msvideo,text/plain,image/png', '允许上传的文件mime', 0, null, null),
       ('upload_allow_type', 'upload', 'local,oss,qnoss,cos', '可用的上传文件方式', 0, null, null),
       ('oss_access_key_id', 'upload', '填你的', '阿里云oss公钥', 0, null, null),
       ('oss_access_key_secret', 'upload', '填你的', '阿里云oss私钥', 0, null, null),
       ('oss_endpoint', 'upload', '填你的', '阿里云oss数据中心', 0, null, null),
       ('oss_bucket', 'upload', '填你的', '阿里云oss空间名称', 0, null, null),
       ('oss_domain', 'upload', '填你的', '阿里云oss访问域名', 0, null, null),
       ('logo_title', 'site', 'EasyAdmin', 'LOGO标题', 0, null, null),
       ('logo_image', 'site', '/static/common/images/logo-1.png', 'logo图片', 0, null, null),
       ('site_name', 'site', 'EasyAdmin后台系统', '站点名称', 0, null, null),
       ('site_ico', 'site', '/favicon.ico', '浏览器图标', 0, null, null),
       ('site_copyright', 'site', '填你的', '版权信息', 0, null, null),
       ('site_beian', 'site', '填你的', '备案信息', 0, null, null),
       ('site_version', 'site', '2.0.0', '版本信息', 0, null, null),
       ('sms_type', 'sms', 'alisms', '短信类型', 0, null, null),
       ('miniapp_appid', 'wechat', '填你的', '小程序公钥', 0, null, null),
       ('miniapp_appsecret', 'wechat', '填你的', '小程序私钥', 0, null, null),
       ('web_appid', 'wechat', '填你的', '公众号公钥', 0, null, null),
       ('web_appsecret', 'wechat', '填你的', '公众号私钥', 0, null, null),
       ('cos_secret_id', 'upload', '填你的', '腾讯云cos密钥', 0, null, null),
       ('cos_secret_key', 'upload', '填你的', '腾讯云cos私钥', 0, null, null),
       ('cos_region', 'upload', '填你的', '存储桶地域', 0, null, null),
       ('cos_bucket', 'upload', '填你的', '存储桶名称', 0, null, null),
       ('qnoss_access_key', 'upload', '填你的', '访问密钥', 0, null, null),
       ('qnoss_secret_key', 'upload', '填你的', '安全密钥', 0, null, null),
       ('qnoss_bucket', 'upload', '填你的', '存储空间', 0, null, null),
       ('qnoss_domain', 'upload', '填你的', '访问域名', 0, null, null);

-- 7. 菜单表
DROP TABLE IF EXISTS "ea_system_menu";
CREATE TABLE "ea_system_menu"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pid" bigint NOT NULL DEFAULT 0,
    "title" varchar(100) NOT NULL DEFAULT '',
    "icon" varchar(100) NOT NULL DEFAULT '',
    "href" varchar(100) NOT NULL DEFAULT '',
    "params" varchar(500) DEFAULT '',
    "target" varchar(20) NOT NULL DEFAULT '_self',
    "sort" int DEFAULT 0,
    "status" smallint NOT NULL DEFAULT 1,
    "remark" varchar(255) DEFAULT NULL,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL
);
CREATE INDEX "ea_idx_system_menu_title" ON "ea_system_menu" ("title");
CREATE INDEX "ea_idx_system_menu_href" ON "ea_system_menu" ("href");

INSERT INTO "ea_system_menu" ("pid", "title", "icon", "href", "params", "target", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES (99999999, '后台首页', 'fa fa-home', 'index/welcome', '', '_self', 0, 1, null, null, 1573120497, null),
       (0, '系统管理', 'fa fa-cog', '', '', '_self', 0, 1, '', null, 1588999529, null),
       (2, '菜单管理', 'fa fa-tree', 'system/menu/index', '', '_self', 10, 1, '', null, 1588228555, null),
       (2, '管理员管理', 'fa fa-user', 'system/admin/index', '', '_self', 12, 1, '', 1573185011, 1588228573, null),
       (2, '角色管理', 'fa fa-square-person-confined', 'system/auth/index', '', '_self', 11, 1, '', 1573435877, 1588228634, null),
       (2, '节点管理', 'fa fa-list', 'system/node/index', '', '_self', 9, 1, '', 1573435919, 1588228648, null),
       (2, '配置管理', 'fa fa-asterisk', 'system/config/index', '', '_self', 8, 1, '', 1573457448, 1588228566, null),
       (2, '上传管理', 'fa fa-arrow-up', 'system/uploadfile/index', '', '_self', 0, 1, '', 1573542953, 1588228043, null),
       (0, '商城管理', 'fa fa-list', '', '', '_self', 0, 1, '', 1589439884, 1589439884, null),
       (9, '商品分类', 'fa fa-calendar-check', 'mall/cate/index', '', '_self', 0, 1, '', 1589439910, 1589439966, null),
       (9, '商品管理', 'fa fa-store-alt', 'mall/goods/index', '', '_self', 0, 1, '', 1589439931, 1589439942, null),
       (2, '快捷入口', 'fa fa-tachometer-alt-fast', 'system/quick/index', '', '_self', 0, 1, '', 1589623683, 1589623683, null),
       (2, '日志管理', 'fa fa-sticky-note', 'system/log/index', '', '_self', 0, 1, '', 1589623684, 1589623684, null),
       (2, 'CURD可视化', 'fa fa fa-shower', 'system/curd_generate/index', '', '_self', 0, 1, '', 1589623684, 1589623684, null),
       (2, '其他页面', 'fa fa-square-share-nodes', '', '', '_self', 0, 1, '', 1589623684, 1589623684, null),
       (15, '官网', 'fa fa-home', 'https://easyadmin8.top', '', '_self', 3, 1, '', 1589623684, 1589623684, null),
       (15, '问答社区', 'fa fa-comments', 'https://easyadmin8.top', '', '_blank', 0, 1, '', 1589623684, 1589623684, null),
       (15, '常见问题', 'fa fa-circle-question', 'https://easyadmin8.top/guide/question.html', '', '_self', 2, 1, '', 1589623684, 1589623684, null),
       (2, '日志分析', 'fa fa-robot', 'system/LogAnalyzer/index', '', '_self', 1, 1, '', 1589623684, 1589623684, null);

-- 8. 节点表
DROP TABLE IF EXISTS "ea_system_node";
CREATE TABLE "ea_system_node"
(
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "node" varchar(100) DEFAULT NULL,
    "title" varchar(500) DEFAULT NULL,
    "type" smallint DEFAULT 3,
    "is_auth" smallint DEFAULT 1,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL
);
CREATE INDEX "ea_idx_system_node_node" ON "ea_system_node" ("node");

INSERT INTO "ea_system_node" ("node", "title", "type", "is_auth", "create_time", "update_time")
VALUES ('system/admin', '管理员管理', 1, 1, 1589580432, 1589580432),
       ('system/admin/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/admin/add', '添加', 2, 1, 1589580432, 1589580432),
       ('system/admin/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/admin/password', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/admin/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('system/admin/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('system/admin/export', '导出', 2, 1, 1589580432, 1589580432),
       ('system/auth', '角色权限管理', 1, 1, 1589580432, 1589580432),
       ('system/auth/authorize', '授权', 2, 1, 1589580432, 1589580432),
       ('system/auth/saveAuthorize', '授权保存', 2, 1, 1589580432, 1589580432),
       ('system/auth/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/auth/add', '添加', 2, 1, 1589580432, 1589580432),
       ('system/auth/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/auth/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('system/auth/export', '导出', 2, 1, 1589580432, 1589580432),
       ('system/auth/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('system/config', '系统配置管理', 1, 1, 1589580432, 1589580432),
       ('system/config/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/config/save', '保存', 2, 1, 1589580432, 1589580432),
       ('system/menu', '菜单管理', 1, 1, 1589580432, 1589580432),
       ('system/menu/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/menu/add', '添加', 2, 1, 1589580432, 1589580432),
       ('system/menu/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/menu/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('system/menu/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('system/menu/getMenuTips', '添加菜单提示', 2, 1, 1589580432, 1589580432),
       ('system/menu/export', '导出', 2, 1, 1589580432, 1589580432),
       ('system/node', '系统节点管理', 1, 1, 1589580432, 1589580432),
       ('system/node/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/node/refreshNode', '系统节点更新', 2, 1, 1589580432, 1589580432),
       ('system/node/clearNode', '清除失效节点', 2, 1, 1589580432, 1589580432),
       ('system/node/add', '添加', 2, 1, 1589580432, 1589580432),
       ('system/node/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/node/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('system/node/export', '导出', 2, 1, 1589580432, 1589580432),
       ('system/node/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile', '上传文件管理', 1, 1, 1589580432, 1589580432),
       ('system/uploadfile/index', '列表', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile/add', '添加', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile/export', '导出', 2, 1, 1589580432, 1589580432),
       ('system/uploadfile/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('mall/cate', '商品分类管理', 1, 1, 1589580432, 1589580432),
       ('mall/cate/index', '列表', 2, 1, 1589580432, 1589580432),
       ('mall/cate/add', '添加', 2, 1, 1589580432, 1589580432),
       ('mall/cate/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('mall/cate/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('mall/cate/export', '导出', 2, 1, 1589580432, 1589580432),
       ('mall/cate/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('mall/goods', '商城商品管理', 1, 1, 1589580432, 1589580432),
       ('mall/goods/index', '列表', 2, 1, 1589580432, 1589580432),
       ('mall/goods/stock', '入库', 2, 1, 1589580432, 1589580432),
       ('mall/goods/add', '添加', 2, 1, 1589580432, 1589580432),
       ('mall/goods/edit', '编辑', 2, 1, 1589580432, 1589580432),
       ('mall/goods/delete', '删除', 2, 1, 1589580432, 1589580432),
       ('mall/goods/export', '导出', 2, 1, 1589580432, 1589580432),
       ('mall/goods/modify', '属性修改', 2, 1, 1589580432, 1589580432),
       ('system/quick', '快捷入口管理', 1, 1, 1589623188, 1589623188),
       ('system/quick/index', '列表', 2, 1, 1589623188, 1589623188),
       ('system/quick/add', '添加', 2, 1, 1589623188, 1589623188),
       ('system/quick/edit', '编辑', 2, 1, 1589623188, 1589623188),
       ('system/quick/delete', '删除', 2, 1, 1589623188, 1589623188),
       ('system/quick/export', '导出', 2, 1, 1589623188, 1589623188),
       ('system/quick/modify', '属性修改', 2, 1, 1589623188, 1589623188),
       ('system/log', '操作日志管理', 1, 1, 1589623188, 1589623188),
       ('system/log/index', '列表', 2, 1, 1589623188, 1589623188),
       ('system/curd_generate', 'CURD可视化管理', 1, 1, 1589623188, 1589623188),
       ('system/curd_generate/index', '列表', 2, 1, 1589623188, 1589623188),
       ('system/curd_generate/save', '操作', 2, 1, 1589623188, 1589623188);

-- 9. 快捷入口表
DROP TABLE IF EXISTS "ea_system_quick";
CREATE TABLE "ea_system_quick"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(20) NOT NULL,
    "icon" varchar(100) DEFAULT NULL,
    "href" varchar(255) DEFAULT NULL,
    "sort" int DEFAULT 0,
    "status" smallint DEFAULT 1,
    "remark" varchar(255) DEFAULT NULL,
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "delete_time" int DEFAULT NULL
);

INSERT INTO "ea_system_quick" ("title", "icon", "href", "sort", "status", "remark", "create_time", "update_time", "delete_time")
VALUES ('管理员管理', 'fa fa-user', 'system/admin/index', 0, 1, '', 1589624097, 1589624792, null),
       ('角色管理', 'fa fa-square-person-confined', 'system/auth/index', 0, 1, '', 1589624772, 1589624781, null),
       ('菜单管理', 'fa fa-tree', 'system/menu/index', 0, 1, null, 1589624097, 1589624792, null),
       ('节点管理', 'fa fa-list', 'system/node/index', 0, 1, null, 1589624772, 1589624781, null),
       ('配置管理', 'fa fa-asterisk', 'system/config/index', 0, 1, null, 1589624097, 1589624792, null),
       ('上传管理', 'fa fa-arrow-up', 'system/uploadfile/index', 0, 1, null, 1589624772, 1589624781, null),
       ('商品分类', 'fa fa-calendar-check', 'mall/cate/index', 0, 1, null, 1589624097, 1589624792, null),
       ('商品管理', 'fa fa-store-alt', 'mall/goods/index', 0, 1, null, 1589624772, 1589624781, null);

-- 10. 文件上传表
DROP TABLE IF EXISTS "ea_system_uploadfile";
CREATE TABLE "ea_system_uploadfile"
(
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "upload_type" varchar(20) NOT NULL DEFAULT 'local',
    "original_name" varchar(255) DEFAULT '',
    "url" varchar(255) NOT NULL DEFAULT '',
    "image_width" varchar(30) NOT NULL DEFAULT '',
    "image_height" varchar(30) NOT NULL DEFAULT '',
    "image_type" varchar(30) NOT NULL DEFAULT '',
    "image_frames" int NOT NULL DEFAULT 0,
    "mime_type" varchar(100) NOT NULL DEFAULT '',
    "file_size" int NOT NULL DEFAULT 0,
    "file_ext" varchar(100) DEFAULT '',
    "sha1" varchar(40) NOT NULL DEFAULT '',
    "create_time" int DEFAULT NULL,
    "update_time" int DEFAULT NULL,
    "upload_time" int DEFAULT NULL
);
CREATE INDEX "ea_idx_system_uploadfile_upload_type" ON "ea_system_uploadfile" ("upload_type");

INSERT INTO "ea_system_uploadfile" ("upload_type", "original_name", "url", "image_width", "image_height", "image_type", "image_frames", "mime_type", "file_size", "file_ext", "sha1", "create_time", "update_time", "upload_time")
VALUES ('oss', 'image/jpeg', 'https://lxn-99php.oss-cn-shenzhen.aliyuncs.com/upload/20191111/0a6de1ac058ee134301501899b84ecb1.jpg', '', '', '', 0, 'image/jpeg', 0, 'jpg', '', 1573612437, null, null),
       ('oss', 'image/jpeg', 'https://lxn-99php.oss-cn-shenzhen.aliyuncs.com/upload/20191111/46d7384f04a3bed331715e86a4095d15.jpg', '', '', '', 0, 'image/jpeg', 0, 'jpg', '', 1573612437, null, null),
       ('oss', 'image/x-icon', 'https://lxn-99php.oss-cn-shenzhen.aliyuncs.com/upload/20191111/7d32671f4c1d1b01b0b28f45205763f9.ico', '', '', '', 0, 'image/x-icon', 0, 'ico', '', 1573612437, null, null),
       ('oss', 'image/jpeg', 'https://lxn-99php.oss-cn-shenzhen.aliyuncs.com/upload/20191111/28cefa547f573a951bcdbbeb1396b06f.jpg', '', '', '', 0, 'image/jpeg', 0, 'jpg', '', 1573612437, null, null),
       ('oss', 'image/jpeg', 'https://lxn-99php.oss-cn-shenzhen.aliyuncs.com/upload/20191111/2c412adf1b30c8be3a913e603c7b6e4a.jpg', '', '', '', 0, 'image/jpeg', 0, 'jpg', '', 1573612437, null, null),
       ('cos', 'image/jpeg', 'https://easyadmin-1251997243.cos.ap-guangzhou.myqcloud.com/upload/20191114/2381eaf81208ac188fa994b6f2579953.jpg', '', '', '', 0, 'image/jpeg', 0, 'jpg', '', 1573612437, null, null);

-- 11. 系统日志表
DROP TABLE IF EXISTS "ea_system_log";
CREATE TABLE "ea_system_log"
(
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id" int DEFAULT 0,
    "url" varchar(1500) NOT NULL DEFAULT '',
    "method" varchar(50) NOT NULL,
    "title" varchar(100) DEFAULT '',
    "content" json NOT NULL,
    "response" json DEFAULT NULL,
    "ip" varchar(50) NOT NULL DEFAULT '',
    "useragent" varchar(255) DEFAULT '',
    "create_time" int DEFAULT NULL
);

DROP TYPE IF EXISTS "public"."tablestruct" CASCADE;
